version: '3.9'

# TODO logi z lokiego nie działają
# TODO skonfigurować pobieranie danych z azure i google cloud w prometheus
# TODO skonfigurować pobieranie danych z azure (15136, 19785) i google cloud do dashboard (12863 )
# TODO uruchomić całośc na google cloud
# TODO uruchomić całośc na azure

# 1. Startujesz monitoring bez k6
#docker compose up -d

# 2. Gdy baza danych / aplikacje są gotowe – uruchamiasz testy
#docker compose --profile loadtests up -d k6-gcp k6-azure k6-local

#Zbieranie pomiarów do pracy magisterskiej:
# - podczas pomiarów uruchoić testy przynajmniej 3 razy
services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--web.enable-remote-write-receiver"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - ./provisioning:/etc/grafana/provisioning
      - grafana_data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=Test123!
      - GRAFANA_TOKEN=${GRAFANA_TOKEN}
      - K6_TEST_START=${TEST_START}
      - GRAFANA_URL=http://grafana:3000
      - RUN_ID=${RUN_ID:-$(date +%s)}
    depends_on:
      - prometheus

  postgres_exporter:
    image: wrouesnel/postgres_exporter
    container_name: postgres_exporter
    environment:
      DATA_SOURCE_NAME: "postgresql://postgres:postgres@host.docker.internal:5432/postgres?sslmode=disable"
    ports:
      - "9187:9187"

#  log_poller:
#    build:
#      context: ./logs/logs-poller
#      dockerfile: Dockerfile
#    ports:
#      - "8002:8002"
#    container_name: log_poller
#    environment:
#      - LOG_ENDPOINT=http://host.docker.internal:8000/logs/
#    volumes:
#      - logs:/var/log
#    healthcheck:
#      test: ["CMD-SHELL", "curl -f http://localhost:8002/health || exit 1"]
#      interval: 15s
#      timeout: 5s
#      retries: 3
#
#  fluentbit:
#    image: fluent/fluent-bit:latest
#    container_name: fluentbit
#    volumes:
#      - ./logs/fluent-bit/fluent-bit.conf:/fluent-bit/etc/fluent-bit.conf:ro
#      - ./logs/fluent-bit/parsers.conf:/fluent-bit/etc/parsers.conf:ro
#      - logs:/var/log
#    depends_on:
#      - log_poller
#
#  loki:
#    image: grafana/loki:2.8.2
#    container_name: loki
#    ports:
#      - "3100:3100"
#    volumes:
#      - loki_data:/loki
#    depends_on:
#      - fluentbit

  k6-base: &common
    build:
      context: ./load-tests
      dockerfile: Dockerfile
    depends_on:
      - prometheus
      - grafana
    deploy:
      resources:
        limits:
          cpus: '4.0'
          memory: 4G
    environment:
      - K6_PROMETHEUS_RW_SERVER_URL=http://host.docker.internal:9090/api/v1/write
      - K6_PROMETHEUS_RW_TREND_STATS=p(95),avg,count
      - GRAFANA_URL=host.docker.internal:3000
      - GRAFANA_TOKEN=${GRAFANA_TOKEN}
    volumes:
      - ./load-tests/tests/:/tests
    profiles: ["loadtests"]

  k6-gcp:
    extends: { service: k6-base }
    environment:
      - BASE_URL=https://service.a.run.app
      - K6_PROMETHEUS_LABELS="cloud=gcp,run=$(date +%s)"

  k6-azure:
    extends: { service: k6-base }
    environment:
      - BASE_URL=https://service.azurewebsites.net
      - K6_PROMETHEUS_LABELS="cloud=azure,run=$(date +%s)"

  k6-local:
    extends: { service: k6-base }
    environment:
      - BASE_URL=http://host.docker.internal:8000
      - K6_PROMETHEUS_LABELS="cloud=local,run=$(date +%s)"

volumes:
  grafana_data: {}
  prometheus_data: {}
  loki_data: {}
  logs: {}