global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'django-local'
    static_configs:
      - targets: ['host.docker.internal:8000']
    relabel_configs:
      - target_label: provider
        replacement: 'local'

  - job_name: 'postgres-local'
    static_configs:
      - targets: ['host.docker.internal:9187']
    metric_relabel_configs:
      - target_label: provider
        replacement: local

#  - job_name: 'django_gcp'
#    static_configs:
#      - targets: ['gcp-host:8000']
#    relabel_configs:
#      - target_label: cloud_provider
#        replacement: 'gcp'
#
#  - job_name: 'django_azure'
#    static_configs:
#      - targets: ['azure-host:8000']
#    relabel_configs:
#      - target_label: cloud_provider
#        replacement: 'azure'
#
#  - job_name: 'django_local'
#    static_configs:
#      - targets: ['127.0.0.1:8000']
#    relabel_configs:
#      - target_label: cloud_provider
#        replacement: 'local'
  # Zbieranie metryk z usługi Cloud Run
#  - job_name: 'cloud_run'
#    metrics_path: '/metrics'
#    scheme: https
#    static_configs:
#      - targets: ['https://cloudrun-pracamagisterska-416944886717.europe-central2.run.app/']
#
#  # Zbieranie metryk z PostgreSQL przez exporter
#  - job_name: 'postgres'
#    static_configs:
#      - targets: ['postgres_exporter:9187']
