global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'django-local'
    static_configs:
      - targets: ['host.docker.internal:8000']
    relabel_configs:
      - target_label: provider
        replacement: 'local'

  - job_name: 'postgres-local'
    static_configs:
      - targets: ['host.docker.internal:9187']
    metric_relabel_configs:
      - target_label: provider
        replacement: 'local'
