global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets:
          - "localhost:9090"

  - job_name: "postgres-gcp"
    static_configs:
      - targets:
          - "host.docker.internal:9187"
        labels:
          app: "postgres-gcp"
          service: "postgres-gcp"
    metric_relabel_configs:
      - target_label: provider
        replacement: "postgres-gcp"

  - job_name: "stackdriver_exporter-gcp"
    metrics_path: "/metrics"
    static_configs:
      - targets:
          - "host.docker.internal:8080"
        labels:
          app: "stackdriver_exporter-gcp"
          service: "stackdriver_exporter-gcp"

  - job_name: "django-gcp"
    scheme: https
    metrics_path: "/metrics"
    static_configs:
      - targets:
          - "praca-magisterska-django-app-1001731509124.europe-central2.run.app"
        labels:
          app: "django-gcp"
          service: "django-gcp"
    tls_config:
      insecure_skip_verify: true
    metric_relabel_configs:
      - target_label: provider
        replacement: "django-gcp"

  #TODO skonfigurować pobieranie metryk z Azure Container App
  - job_name: "azure_webapp_metrics"
    scrape_interval: 60s
    metrics_path: /probe/metrics/list
    params:
      subscription: ["${AZURE_SUBSCRIPTION_ID_PRIVATE}"]
      resourceType: ["Microsoft.Web/sites"]
      metric: ["CpuTime", "HttpRequests", "MemoryWorkingSet"]
      interval: ["PT1M"]
      aggregation: ["average"]
    static_configs:
      - targets: ["azure-metrics-exporter:8081"]
