global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets:
          - "localhost:9090"

  #  - job_name: "postgres-gcp"
  #    static_configs:
  #      - targets:
  #          - "host.docker.internal:9187"
  #        labels:
  #          app: "postgres-gcp"
  #          service: "postgres-gcp"
  #    metric_relabel_configs:
  #      - target_label: provider
  #        replacement: "postgres-gcp"

  #  - job_name: "django-gcp"
  #    scheme: https
  #    metrics_path: "/metrics"
  #    static_configs:
  #      - targets:
  #          - "praca-magisterska-django-app-1001731509124.europe-central2.run.app"
  #        labels:
  #          app: "django-gcp"
  #          service: "django-gcp"
  #    tls_config:
  #      insecure_skip_verify: true
  #    metric_relabel_configs:
  #      - target_label: provider
  #        replacement: "django-gcp"

  - job_name: "stackdriver_exporter-gcp"
    metrics_path: "/metrics"
    static_configs:
      - targets:
          - "host.docker.internal:8080"
        labels:
          app: "stackdriver_exporter-gcp"
          service: "stackdriver_exporter-gcp"

  - job_name: "azure-metrics-exporter"
    metrics_path: "/metrics"
    static_configs:
      - targets:
          - "host.docker.internal:8081"
        labels:
          app: "azure-metrics-exporte"
          service: "azure-metrics-exporte"

  - job_name: "azure_containerapps_low"
    scrape_interval: 60s
    metrics_path: /probe/metrics/list
    params:
      subscription: ["a0714776-778a-4668-917f-b22059efed7f"]
      resource:
        - "/subscriptions/a0714776-778a-4668-917f-b22059efed7f/resourceGroups/praca-magisterska-proj-azure/providers/Microsoft.App/containerApps/low-r405e"
      metricNamespace: ["Microsoft.App/containerApps"]
      resourceType: ["Microsoft.App/containerApps"]
      metric: [
          "UsageNanoCores", # CPU usage (nano cores) ~ odpowiednik cpu/usage
          "CpuPercentage", # CPU utilization ~ odpowiednik cpu/utilizations
          "WorkingSetBytes", # Memory usage (bytes) ~ odpowiednik memory/usage
          "MemoryPercentage", # Memory utilization ~ odpowiednik memory/utilizations
          "RxBytes", # Network received bytes ~ received_bytes_count
          "TxBytes", # Network sent bytes ~ sent_bytes_count
          "Requests", # Żądania (jeśli app je eksponuje w Azure Monitor)
          "Replicas", # Instance count ~ instance_count
        ]
      interval: ["PT1M"]
      timespan: ["PT5M"]
      aggregation: ["Average", "Total"]
    static_configs:
      - targets: ["azure-metrics-exporter:8080"]
        labels:
          app: "aca-low"
          service: "aca-low"
          provider: "azure"

  - job_name: "azure_containerapps_medium"
    scrape_interval: 60s
    metrics_path: /probe/metrics/list
    params:
      subscription: ["a0714776-778a-4668-917f-b22059efed7f"]
      resource:
        - "/subscriptions/a0714776-778a-4668-917f-b22059efed7f/resourceGroups/praca-magisterska-proj-azure/providers/Microsoft.App/containerApps/medium-r405e"
      metricNamespace: ["Microsoft.App/containerApps"]
      resourceType: ["Microsoft.App/containerApps"]
      metric: [
          "UsageNanoCores", # CPU usage (nano cores) ~ odpowiednik cpu/usage
          "CpuPercentage", # CPU utilization ~ odpowiednik cpu/utilizations
          "WorkingSetBytes", # Memory usage (bytes) ~ odpowiednik memory/usage
          "MemoryPercentage", # Memory utilization ~ odpowiednik memory/utilizations
          "RxBytes", # Network received bytes ~ received_bytes_count
          "TxBytes", # Network sent bytes ~ sent_bytes_count
          "Requests", # Żądania (jeśli app je eksponuje w Azure Monitor)
          "Replicas", # Instance count ~ instance_count
        ]
      interval: ["PT1M"]
      timespan: ["PT5M"]
      aggregation: ["Average", "Total"]
    static_configs:
      - targets: ["azure-metrics-exporter:8080"]
        labels:
          app: "aca-medium"
          service: "aca-medium"
          provider: "azure"

  - job_name: "azure_containerapps_high"
    scrape_interval: 60s
    metrics_path: /probe/metrics/list
    params:
      subscription: ["a0714776-778a-4668-917f-b22059efed7f"]
      resource:
        - "/subscriptions/a0714776-778a-4668-917f-b22059efed7f/resourceGroups/praca-magisterska-proj-azure/providers/Microsoft.App/containerApps/high-r405e"
      metricNamespace: ["Microsoft.App/containerApps"]
      resourceType: ["Microsoft.App/containerApps"]
      metric: [
          "UsageNanoCores", # CPU usage (nano cores) ~ odpowiednik cpu/usage
          "CpuPercentage", # CPU utilization ~ odpowiednik cpu/utilizations
          "WorkingSetBytes", # Memory usage (bytes) ~ odpowiednik memory/usage
          "MemoryPercentage", # Memory utilization ~ odpowiednik memory/utilizations
          "RxBytes", # Network received bytes ~ received_bytes_count
          "TxBytes", # Network sent bytes ~ sent_bytes_count
          "Requests", # Żądania (jeśli app je eksponuje w Azure Monitor)
          "Replicas", # Instance count ~ instance_count
        ]
      interval: ["PT1M"]
      timespan: ["PT5M"]
      aggregation: ["Average", "Total"]
    static_configs:
      - targets: ["azure-metrics-exporter:8080"]
        labels:
          app: "aca-high"
          service: "aca-high"
          provider: "azure"
rule_files:
  - rules/startup.rules.yml
