{
 "title": "Kontener Aplikacji 09092025",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Maksymalne wykorzystanie CPU [99-ty percentyl] -  Wykorzystanie Procesora",
   "type": "timeseries",
   "description": "P99 (0.99)\n– 99 % pomiarów było ≤ tej wartości.\n– pokazuje niemal maksymalne obciążenie — odsiewa tylko tę najbardziej ekstremalną 1 %.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "histogram_quantile(\r\n  0.99,\r\n  sum by (le)(\r\n    rate(\r\n      stackdriver_cloud_run_revision_run_googleapis_com_container_cpu_utilizations_bucket{\r\n        service_name=\"praca-magisterska-django-app\"\r\n      }[30m]\r\n    )\r\n  )\r\n) * 100",
     "legendFormat": "Cloud run"
    },
    {
     "expr": "quantile_over_time(\r\n  0.99,\r\n  (\r\n    avg by (resourceName) (\r\n      azurerm_resource_metric{\r\n        metric=\"CpuPercentage\",\r\n        aggregation=\"average\"\r\n      }\r\n    )\r\n  )[30m:1m]\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Maksymalne wykorzystanie RAM [99-ty percentyl] - Wykorzystanie Pamięci",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
   "targets": [
    {
     "expr": "histogram_quantile(\r\n  0.99,\r\n  sum by (le)(\r\n    rate(\r\n      stackdriver_cloud_run_revision_run_googleapis_com_container_memory_utilizations_bucket{\r\n        service_name=\"praca-magisterska-django-app\"\r\n      }[30m]\r\n    )\r\n  )\r\n) * 100\r\n",
     "legendFormat": "Cloud Run"
    },
    {
     "expr": "quantile_over_time(\r\n  0.99,\r\n  (\r\n    avg by (resourceName) (\r\n      azurerm_resource_metric{\r\n        metric=\"MemoryPercentage\",\r\n        aggregation=\"average\"\r\n      }\r\n    )\r\n  )[30m:1m]\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Czas oczekiwania na uruchomienie kontenera [99-ty percentyl] ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
   "targets": [
    {
     "expr": "histogram_quantile(\r\n  0.99,\r\n  sum by (le)(\r\n    rate(\r\n      stackdriver_cloud_run_revision_run_googleapis_com_container_startup_latencies_bucket{\r\n        service_name=\"praca-magisterska-django-app\"\r\n      }[30m]\r\n    )\r\n  )\r\n) * 100\r\n",
     "legendFormat": "Cloud Run"
    },
    {
     "expr": "quantile_over_time(\r\n  0.99,\r\n  (  avg by (resourceName) (\r\n  aca_startup_pending_seconds_by_app{}\r\n  ))[30m:1m]\r\n\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Maksymalne wykorzystanie CPU  [95-ty percentyl] -  Wykorzystanie Procesora",
   "type": "timeseries",
   "description": "P95 (0.95)\n– 95 % pomiarów CPU było ≤ tej wartości.\n– czyli tylko 5 % chwil było cięższych (wyższego obciążenia) — dobrze wyłapuje krótkie skoki, ale ignoruje rzadkie szpilki.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "histogram_quantile(\r\n  0.95,\r\n  sum by (le)(\r\n    rate(\r\n      stackdriver_cloud_run_revision_run_googleapis_com_container_cpu_utilizations_bucket{\r\n        service_name=\"praca-magisterska-django-app\"\r\n      }[30m]\r\n    )\r\n  )\r\n) * 100",
     "legendFormat": "Cloud run"
    },
    {
     "expr": "quantile_over_time(\r\n  0.95,\r\n  (\r\n    avg by (resourceName) (\r\n      azurerm_resource_metric{\r\n        metric=\"CpuPercentage\",\r\n        aggregation=\"average\"\r\n      }\r\n    )\r\n  )[30m:1m]\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Maksymalne wykorzystanie RAM  [95-ty percentyl] - Wykorzystanie Pamięci",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 8 },
   "targets": [
    {
     "expr": "histogram_quantile(\r\n  0.95,\r\n  sum by (le)(\r\n    rate(\r\n      stackdriver_cloud_run_revision_run_googleapis_com_container_memory_utilizations_bucket{\r\n        service_name=\"praca-magisterska-django-app\"\r\n      }[30m]\r\n    )\r\n  )\r\n) * 100\r\n",
     "legendFormat": "Cloud Run"
    },
    {
     "expr": "quantile_over_time(\r\n  0.95,\r\n  (\r\n    avg by (resourceName) (\r\n      azurerm_resource_metric{\r\n        metric=\"MemoryPercentage\",\r\n        aggregation=\"average\"\r\n      }\r\n    )\r\n  )[30m:1m]\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Czas oczekiwania na uruchomienie kontenera [95-ty percentyl] ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 8 },
   "targets": [
    {
     "expr": "histogram_quantile(\r\n  0.95,\r\n  sum by (le)(\r\n    rate(\r\n      stackdriver_cloud_run_revision_run_googleapis_com_container_startup_latencies_bucket{\r\n        service_name=\"praca-magisterska-django-app\"\r\n      }[30m]\r\n    )\r\n  )\r\n) * 100\r\n",
     "legendFormat": "Cloud Run"
    },
    {
     "expr": "quantile_over_time(\r\n  0.95,\r\n  (  avg by (resourceName) (\r\n  aca_startup_pending_seconds_by_app{}\r\n  ))[30m:1m]\r\n\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Maksymalne wykorzystanie CPU [50-ty percentyl] -  Wykorzystanie Procesora",
   "type": "timeseries",
   "description": "P50 (0.50)\n– mówi ci, że połowa pomiarów w ciągu ostatnich 30 min miała CPU ≤ tej wartości.\n– to mediana obciążenia — pomocna, jeśli chcesz wiedzieć, jak „typowo” wygląda zużycie.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "histogram_quantile(\r\n  0.5,\r\n  sum by (le)(\r\n    rate(\r\n      stackdriver_cloud_run_revision_run_googleapis_com_container_cpu_utilizations_bucket{\r\n        service_name=\"praca-magisterska-django-app\"\r\n      }[30m]\r\n    )\r\n  )\r\n) * 100",
     "legendFormat": "Cloud run"
    },
    {
     "expr": "quantile_over_time(\r\n  0.50,\r\n  (\r\n    avg by (resourceName) (\r\n      azurerm_resource_metric{\r\n        metric=\"CpuPercentage\",\r\n        aggregation=\"average\"\r\n      }\r\n    )\r\n  )[30m:1m]\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Maksymalne wykorzystanie RAM [50-ty percentyl]  - Wykorzystanie Pamięci",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 16 },
   "targets": [
    {
     "expr": "histogram_quantile(\r\n  0.5,\r\n  sum by (le)(\r\n    rate(\r\n      stackdriver_cloud_run_revision_run_googleapis_com_container_memory_utilizations_bucket{\r\n        service_name=\"praca-magisterska-django-app\"\r\n      }[30m]\r\n    )\r\n  )\r\n) * 100\r\n",
     "legendFormat": "Cloud Run"
    },
    {
     "expr": "quantile_over_time(\r\n  0.5,\r\n  (\r\n    avg by (resourceName) (\r\n      azurerm_resource_metric{\r\n        metric=\"MemoryPercentage\",\r\n        aggregation=\"average\"\r\n      }\r\n    )\r\n  )[30m:1m]\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Czas oczekiwania na uruchomienie kontenera [50-ty percentyl] ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 16 },
   "targets": [
    {
     "expr": "histogram_quantile(\r\n  0.5,\r\n  sum by (le)(\r\n    rate(\r\n      stackdriver_cloud_run_revision_run_googleapis_com_container_startup_latencies_bucket{\r\n        service_name=\"praca-magisterska-django-app\"\r\n      }[30m]\r\n    )\r\n  )\r\n) * 100\r\n",
     "legendFormat": "Cloud Run"
    },
    {
     "expr": "quantile_over_time(\r\n  0.5,\r\n  (  avg by (resourceName) (\r\n  aca_startup_pending_seconds_by_app{}\r\n  ))[30m:1m]\r\n\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Odchylenie standardowe -  Wykorzystanie Procesora",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "stddev_over_time(\r\n  rate(\r\n    stackdriver_cloud_run_revision_run_googleapis_com_container_cpu_utilizations_sum{\r\n      service_name=\"praca-magisterska-django-app\"\r\n    }[5m]\r\n  )[30m:1m]\r\n)",
     "legendFormat": "Cloud Run"
    },
    {
     "expr": "stddev_over_time(\r\n(\r\n    sum by (resourceName) (\r\n      azurerm_resource_metric{\r\n        metric=\"CpuPercentage\",\r\n        aggregation=\"total\"\r\n      }\r\n    )\r\n  )[30m:1m]\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Odchylenie standardowe RAM - Wykorzystanie Pamięci",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 24 },
   "targets": [
    {
     "expr": "stddev_over_time(\r\n  rate(\r\n    stackdriver_cloud_run_revision_run_googleapis_com_container_memory_utilizations_sum{\r\n      service_name=\"praca-magisterska-django-app\"\r\n    }[5m]\r\n  )[30m:1m]\r\n)",
     "legendFormat": "Cloud Run"
    },
    {
     "expr": "stddev_over_time(\r\n(\r\n    sum by (resourceName) (\r\n      azurerm_resource_metric{\r\n        metric=\"MemoryPercentage\",\r\n        aggregation=\"total\"\r\n      }\r\n    )\r\n  )[30m:1m]\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Odchylenie standardowe - Czas oczekiwania na uruchomienie kontenera",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 24 },
   "targets": [
    {
     "expr": "stddev_over_time(\r\n  rate(\r\n    stackdriver_cloud_run_revision_run_googleapis_com_container_startup_latencies_sum{\r\n      service_name=\"praca-magisterska-django-app\"\r\n    }[5m]\r\n  )[30m:1m]\r\n)",
     "legendFormat": "Cloud Run"
    },
    {
     "expr": "stddev_over_time(\r\n(\r\n    sum by (resourceName) (\r\n  aca_startup_pending_seconds_by_app{}\r\n\r\n    )\r\n  )[30m:1m]\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Wariancja -  Wykorzystanie Procesora",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "stdvar_over_time(\r\n  (\r\n    rate(\r\n      stackdriver_cloud_run_revision_run_googleapis_com_container_cpu_utilizations_sum{\r\n        service_name=\"praca-magisterska-django-app\"\r\n      }[5m]\r\n    )\r\n  )[30m:1m]\r\n)\r\n",
     "legendFormat": "Cloud Run"
    },
    {
     "expr": "stdvar_over_time(\r\n(\r\n    sum by (resourceName) (\r\n      azurerm_resource_metric{\r\n        metric=\"CpuPercentage\",\r\n        aggregation=\"total\"\r\n      }\r\n    )\r\n  )[30m:1m]\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Wariancja RAM - Wykorzystanie Pamięci",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 32 },
   "targets": [
    {
     "expr": "stdvar_over_time(\r\n  rate(\r\n    stackdriver_cloud_run_revision_run_googleapis_com_container_memory_utilizations_sum{\r\n      service_name=\"praca-magisterska-django-app\"\r\n    }[5m]\r\n  )[30m:1m]\r\n)\r\n",
     "legendFormat": "Cloud Run"
    },
    {
     "expr": "stdvar_over_time(\r\n(\r\n    sum by (resourceName) (\r\n      azurerm_resource_metric{\r\n        metric=\"MemoryPercentage\",\r\n        aggregation=\"total\"\r\n      }\r\n    )\r\n  )[30m:1m]\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Wariancja - Czas oczekiwania na uruchomienie kontenera",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 32 },
   "targets": [
    {
     "expr": "stdvar_over_time(\r\n  rate(\r\n    stackdriver_cloud_run_revision_run_googleapis_com_container_startup_latencies_sum{\r\n      service_name=\"praca-magisterska-django-app\"\r\n    }[5m]\r\n  )[30m:1m]\r\n)",
     "legendFormat": "Cloud Run"
    },
    {
     "expr": "stdvar_over_time(\r\n(\r\n    sum by (resourceName) (\r\n  aca_startup_pending_seconds_by_app{}\r\n    )\r\n  )[30m:1m]\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Wychodzące bajty na sekundę - Network I/O",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 40 },
   "targets": [
    {
     "expr": "sum(\r\n  rate(\r\n    stackdriver_cloud_run_revision_run_googleapis_com_container_network_sent_bytes_count{\r\n        service_name=\"praca-magisterska-django-app\"\r\n    }[30m]\r\n  )\r\n)\r\n",
     "legendFormat": "Cloud Run"
    },
    {
     "expr": "sum by (resourceName)(\r\n  rate(\r\n      azurerm_resource_metric{\r\n        metric=\"TxBytes\",\r\n        aggregation=\"total\"\r\n      }[30m]\r\n  )\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Przychodzące bajty na sekundę - Network I/O",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 40 },
   "targets": [
    {
     "expr": "sum(\r\n  rate(\r\n    stackdriver_cloud_run_revision_run_googleapis_com_container_network_received_bytes_count{\r\n        service_name=\"praca-magisterska-django-app\"\r\n    }[30m]\r\n  )\r\n)\r\n",
     "legendFormat": "Cloud Run"
    },
    {
     "expr": "sum by (resourceName)(\r\n  rate(\r\n      azurerm_resource_metric{\r\n        metric=\"RxBytes\",\r\n        aggregation=\"total\"\r\n      }[30m]\r\n  )\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Liczba aktywnych instancji [Średnia]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 40 },
   "targets": [
    {
     "expr": "sum(\r\n  stackdriver_cloud_run_revision_run_googleapis_com_container_instance_count{\r\n    service_name=\"praca-magisterska-django-app\",\r\n    state=\"active\"\r\n  }\r\n) by (service_name)\r\n",
     "legendFormat": "Cloud Run"
    },
    {
     "expr": "avg(\r\n  azurerm_resource_metric{metric=\"Replicas\", aggregation=\"average\"}\r\n) by (resourceName)\r\n",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}